"""add_crm_tables

Revision ID: 5588ed200b6e
Revises: 5f2ed6bc23b1
Create Date: 2026-06-10 23:33:10.834015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5588ed200b6e'
down_revision: Union[str, Sequence[str], None] = '5f2ed6bc23b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_customers_company'), 'crm_customers', ['company'], unique=False)
    op.create_index(op.f('ix_crm_customers_id'), 'crm_customers', ['id'], unique=False)
    op.create_index(op.f('ix_crm_customers_name'), 'crm_customers', ['name'], unique=False)
    op.create_table('crm_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_crm_products_id'), 'crm_products', ['id'], unique=False)
    op.create_index(op.f('ix_crm_products_name'), 'crm_products', ['name'], unique=False)
    op.create_table('crm_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_audit_logs_event_type'), 'crm_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_crm_audit_logs_id'), 'crm_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_crm_audit_logs_session_id'), 'crm_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_crm_audit_logs_user_id'), 'crm_audit_logs', ['user_id'], unique=False)
    op.create_table('crm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_created_by_id'), 'crm_leads', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_customer_id'), 'crm_leads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_id'), 'crm_leads', ['id'], unique=False)
    op.create_table('crm_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_opportunities_created_by_id'), 'crm_opportunities', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_crm_opportunities_customer_id'), 'crm_opportunities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_opportunities_id'), 'crm_opportunities', ['id'], unique=False)
    op.create_table('crm_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['crm_opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_meetings_created_by_id'), 'crm_meetings', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_crm_meetings_customer_id'), 'crm_meetings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_meetings_id'), 'crm_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_crm_meetings_opportunity_id'), 'crm_meetings', ['opportunity_id'], unique=False)
    op.create_table('crm_opportunity_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['crm_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['crm_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_opportunity_items_id'), 'crm_opportunity_items', ['id'], unique=False)
    op.create_index(op.f('ix_crm_opportunity_items_opportunity_id'), 'crm_opportunity_items', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_crm_opportunity_items_product_id'), 'crm_opportunity_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_opportunity_items_product_id'), table_name='crm_opportunity_items')
    op.drop_index(op.f('ix_crm_opportunity_items_opportunity_id'), table_name='crm_opportunity_items')
    op.drop_index(op.f('ix_crm_opportunity_items_id'), table_name='crm_opportunity_items')
    op.drop_table('crm_opportunity_items')
    op.drop_index(op.f('ix_crm_meetings_opportunity_id'), table_name='crm_meetings')
    op.drop_index(op.f('ix_crm_meetings_id'), table_name='crm_meetings')
    op.drop_index(op.f('ix_crm_meetings_customer_id'), table_name='crm_meetings')
    op.drop_index(op.f('ix_crm_meetings_created_by_id'), table_name='crm_meetings')
    op.drop_table('crm_meetings')
    op.drop_index(op.f('ix_crm_opportunities_id'), table_name='crm_opportunities')
    op.drop_index(op.f('ix_crm_opportunities_customer_id'), table_name='crm_opportunities')
    op.drop_index(op.f('ix_crm_opportunities_created_by_id'), table_name='crm_opportunities')
    op.drop_table('crm_opportunities')
    op.drop_index(op.f('ix_crm_leads_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_customer_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_created_by_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_crm_audit_logs_user_id'), table_name='crm_audit_logs')
    op.drop_index(op.f('ix_crm_audit_logs_session_id'), table_name='crm_audit_logs')
    op.drop_index(op.f('ix_crm_audit_logs_id'), table_name='crm_audit_logs')
    op.drop_index(op.f('ix_crm_audit_logs_event_type'), table_name='crm_audit_logs')
    op.drop_table('crm_audit_logs')
    op.drop_index(op.f('ix_crm_products_name'), table_name='crm_products')
    op.drop_index(op.f('ix_crm_products_id'), table_name='crm_products')
    op.drop_table('crm_products')
    op.drop_index(op.f('ix_crm_customers_name'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_id'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_company'), table_name='crm_customers')
    op.drop_table('crm_customers')
    # ### end Alembic commands ###
