"""add_beyoutify_skincare_tables

Revision ID: f6857dcc0ca7
Revises: 9ddf86c5afb2
Create Date: 2026-04-07 19:12:54.688987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6857dcc0ca7'
down_revision: Union[str, Sequence[str], None] = '9ddf86c5afb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skin_type', sa.String(length=50), nullable=False),
    sa.Column('concerns', sa.JSON(), nullable=False),
    sa.Column('current_routine_type', sa.String(length=50), nullable=False),
    sa.Column('current_products', sa.JSON(), nullable=False),
    sa.Column('past_products_6months', sa.JSON(), nullable=False),
    sa.Column('skin_goals', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_profiles_id'), 'skin_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_skin_profiles_user_id'), 'skin_profiles', ['user_id'], unique=True)
    op.create_table('skin_routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skin_profile_id', sa.Integer(), nullable=False),
    sa.Column('am_routine', sa.JSON(), nullable=False),
    sa.Column('pm_routine', sa.JSON(), nullable=False),
    sa.Column('tips', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skin_profile_id'], ['skin_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_routines_id'), 'skin_routines', ['id'], unique=False)
    op.create_index(op.f('ix_skin_routines_user_id'), 'skin_routines', ['user_id'], unique=False)
    op.create_table('routine_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('am_completed', sa.Boolean(), nullable=False),
    sa.Column('pm_completed', sa.Boolean(), nullable=False),
    sa.Column('skin_feeling', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['skin_routines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_logs_date'), 'routine_logs', ['date'], unique=False)
    op.create_index(op.f('ix_routine_logs_id'), 'routine_logs', ['id'], unique=False)
    op.create_index(op.f('ix_routine_logs_user_id'), 'routine_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routine_logs_user_id'), table_name='routine_logs')
    op.drop_index(op.f('ix_routine_logs_id'), table_name='routine_logs')
    op.drop_index(op.f('ix_routine_logs_date'), table_name='routine_logs')
    op.drop_table('routine_logs')
    op.drop_index(op.f('ix_skin_routines_user_id'), table_name='skin_routines')
    op.drop_index(op.f('ix_skin_routines_id'), table_name='skin_routines')
    op.drop_table('skin_routines')
    op.drop_index(op.f('ix_skin_profiles_user_id'), table_name='skin_profiles')
    op.drop_index(op.f('ix_skin_profiles_id'), table_name='skin_profiles')
    op.drop_table('skin_profiles')
    # ### end Alembic commands ###
